#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set natural scroll
TPADID=$(xinput list | grep 'DELL097D:00 04F3:311C Touchpad' | cut -d '=' -f 2 | cut -f 1)
SCROLLID=$(xinput list-props "${TPADID}" | grep "Natural Scrolling Enabled (" | cut -d '(' -f 2 | cut -d ')' -f 1)
TAPCLICKID=$(xinput list-props "${TPADID}" | grep "Tapping Enabled" | cut -d '(' -f 2 | cut -d ')' -f 1)
xinput set-prop "${TPADID}" "${SCROLLID}" 1
xinput set-prop "${TPADID}" "${TAPCLICKID}" 1
#xinput set-prop 11 310 1

nitrogen --restore &
picom &
sxhkd &
polybar &
xsetroot -cursor_name left_ptr &
exec bspwm
# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login
